### ISSUE TITLE
Docker security

### ISSUE THREAD

**Issue by piypil** [piypil/stiefmutterchen#8]
Think about dockers' security. Retrieved [from](https://docs.docker.com/engine/scan/).To issue make notes.

**Comment by safdtgx** [comment]
[trivy](https://github.com/aquasecurity/trivy)
Targets (what Trivy can scan):

- Container Image
- Filesystem
- Git Repository (remote)
- Virtual Machine Image
- Kubernetes
- AWS

Scanners (what Trivy can find there):

- OS packages and software dependencies in use (SBOM)
- Known vulnerabilities (CVEs)
- IaC issues and misconfigurations
- Sensitive information and secrets
- Software licenses
______________________________________________
[grype](https://github.com/anchore/grype)

- Scan the contents of a container image or filesystem to find known vulnerabilities.
- Find vulnerabilities for major operating system packages:
  - Alpine
  - Amazon Linux
  - BusyBox
  - CentOS
  - Debian
  - Distroless
  - Oracle Linux
  - Red Hat (RHEL)
  - Ubuntu
- Find vulnerabilities for language-specific packages:
  - Ruby (Gems)
  - Java (JAR, WAR, EAR, JPI, HPI)
  - JavaScript (NPM, Yarn)
  - Python (Egg, Wheel, Poetry, requirements.txt/setup.py files)
  - Dotnet (deps.json)
  - Golang (go.mod)
  - PHP (Composer)
  - Rust (Cargo)
Supports Docker, OCI and [Singularity](https://github.com/sylabs/singularity) image formats.

Grype's using database

- Alpine Linux SecDB: https://secdb.alpinelinux.org/
- Amazon Linux ALAS: https://alas.aws.amazon.com/AL2/alas.rss
- RedHat RHSAs: https://www.redhat.com/security/data/oval/
- Debian Linux CVE Tracker: https://security-tracker.debian.org/tracker/data/json
- Github GHSAs: https://github.com/advisories
- National Vulnerability Database (NVD): https://nvd.nist.gov/vuln/data-feeds
- Oracle Linux OVAL: https://linux.oracle.com/security/oval/
- RedHat Linux Security Data: https://access.redhat.com/hydra/rest/securitydata/
- Suse Linux OVAL: https://ftp.suse.com/pub/projects/security/oval/
- Ubuntu Linux Security: https://people.canonical.com/~ubuntu-security/

**Comment by piypil** [comment]
@safdtgx 
[lynis](https://cisofy.com/lynis/)
[docker-bench-security](https://github.com/docker/docker-bench-security)
[docker-bench-test](https://github.com/alexei-led/docker-bench-test)
[dockle](https://github.com/goodwithtech/dockle)
