### ISSUE TITLE
Nasty Docker

### ISSUE THREAD

**Issue by piypil** [piypil/stiefmutterchen#9]
There are many different insecure applications. We need to build one docker out of them. 

[dvpwa](https://github.com/anxolerd/dvpwa)
[WebGoat](https://github.com/WebGoat/WebGoat)
[juice-shop](https://github.com/juice-shop/juice-shop)
[mutillidae](https://github.com/webpwnized/mutillidae)
[DVWA](https://github.com/digininja/DVWA)

**Comment by safdtgx** [comment]
- [x] dvpwa
- [x] WebGoat
- [x] juice-shop
- [x] mutillidae
- [x] DVWA

**Comment by piypil** [comment]
Thank you very much @safdtgx
